groups:
  - name: alert.rules
    rules:
      - alert: GreetingsMissing
        expr: increase(http_server_requests_seconds_count{status="200", uri="/greeting"}[12h])<1
        for: 12h
        labels:
          severity: "critical"
        annotations:
          summary: "Endpoint {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes."
