global:
  scrape_interval:     5s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
rule_files:
  - "prometheus.rules.yml"
scrape_configs:
  - job_name: 'promalerts'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8080']

